# ################################
# Authors:
# * Yang Wang 2021
# ################################


seed: 914


# Training parameters
n_jobs: 0
number_of_epochs: 100
train_batch_size: 64
valid_batch_size: 64
lr: 0.0003


# Model parameters
dropout: 0.1
emb_size: 512


# Feature parameters
sample_rate: 16000
n_fft: 400          # sample_rate * window_duration (s)
hop_length: 160     # sample_rate * overlap_duration (s)
n_mels: 80
n_mfcc: 20


compute_features: !new:demixing.feats.transforms.MFCC
    sample_rate: !ref <sample_rate>
    n_mfcc: !ref <n_mfcc>
    melkwargs: 
        n_fft: !ref <n_fft>
        n_mels: !ref <n_mels>
        hop_length: !ref <hop_length>


enc: !new:demixing.nnets.xvector.XVector
    n_mfcc: !ref <n_mfcc>
    dropout: !ref <dropout>


opt_class: !name:transformers.AdamW
    lr: !ref <lr>